package cli

import "winc/internal/ui"

func usage() {
	ui.Say("")
	ui.Say("winc - local Claude Code models (winc.cpp), one portable binary")
	ui.Say("")
	ui.Say("  winc setup                      first-run install wizard")
	ui.Say("  winc detect                     show detected GPU/VRAM + recommended tier")
	ui.Say("  winc ls                         list downloaded + available models")
	ui.Say("  winc -d <alias>                 download a catalogue model")
	ui.Say("  winc -d <repo> <file>           download any GGUF from HuggingFace")
	ui.Say("  winc -r <model> [-y]            delete a downloaded model")
	ui.Say("  winc -s claude <model>          start Claude Code on a local model")
	ui.Say("  winc -s opencode <model>        start OpenCode")
	ui.Say("  winc -s openclaw <model>        start OpenClaw")
	ui.Say("  winc -s cli <model>             raw llama.cpp chat")
	ui.Say("        [--noteam] [--multi] [--reasoning adaptive|on|off|fixed]")
	ui.Say("        team mode is DEFAULT on a big model: subagents start on a small CPU worker")
	ui.Say("        and escalate by load; web search is pre-approved; --noteam = single model")
	ui.Say("  winc serve [--multi]            run the server(s)/router only")
	ui.Say("        [--journal[=off]]         context virtualization: long chats stay fast on a small")
	ui.Say("        live prompt; old turns are stored + recalled on demand (also for -s)")
	ui.Say("  winc journal [ls|show|rm|path]  inspect the conversation store (plaintext, local)")
	ui.Say("  winc doctor                     health snapshot: hardware, engine, models, logs")
	ui.Say("  winc logs [name] [--bundle]     show log tails; --bundle zips a support archive")
	ui.Say("  winc -c | check                 check for updates")
	ui.Say("  winc -u | update                update winc + engine + catalog; reconcile winc.toml")
	ui.Say("  winc -n | uninstall [-y]        remove installed components")
	ui.Say("  winc -v | version               show winc version")
	ui.Say("  winc help                       this help")
	ui.Say("")
	ui.Say("  All settings live in one file: winc.toml")
	ui.Say("  <model> is a catalogue alias (see 'winc ls') or part of a filename.")
	ui.Say("")
}
