package engine

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"winc/internal/config"
	"winc/internal/paths"
	"winc/internal/platform"
)

func quoteArg(s string) string {
	if strings.ContainsAny(s, " \t") {
		return "\"" + s + "\""
	}
	return s
}

// GenerateSwapYAML writes llama-swap.yaml: one tuned llama-server command per
// downloaded model (key -> gguf path), with ${PORT} for llama-swap to substitute
// and a TTL to unload idle models. Returns the written path.
func GenerateSwapYAML(cfg *config.Config, hw platform.Hardware, serverBin string, models map[string]string, ttl int) (string, error) {
	keys := make([]string, 0, len(models))
	for k := range models {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by winc - do not edit by hand (edit winc.toml instead).\n")
	b.WriteString("models:\n")
	for _, k := range keys {
		ctx := ResolveContext(cfg, hw, models[k], FileMB(models[k]), WillOffloadExperts(cfg, hw, models[k]))
		args := ServerArgs(cfg, hw, models[k], 0, "${PORT}", ctx)
		args = append(args, MTPArgs(cfg, hw, models[k], serverBin)...) // MTP variant -> --spec-type draft-mtp (if supported)
		cmd := quoteArg(serverBin)
		for _, a := range args {
			cmd += " " + quoteArg(a)
		}
		b.WriteString("  \"" + k + "\":\n")
		b.WriteString("    cmd: |\n")
		b.WriteString("      " + cmd + "\n")
		if ttl > 0 {
			b.WriteString(fmt.Sprintf("    ttl: %d\n", ttl))
		}
	}
	out := paths.LlamaSwapYAML()
	return out, os.WriteFile(out, []byte(b.String()), 0o644)
}
