package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"winc/internal/paths"
	"winc/internal/search"
)

// preApprovedTools are pre-allowed in the sandbox settings.json so the local agent (and
// every subagent it spawns, including Workflow fan-out) never prompts to use them each
// launch -- winc's local web search, web fetch, plus read-only inspection. Write/Edit/Bash
// stay prompt-on-use; the user's own deny rules still take precedence over these allows.
var preApprovedTools = []string{search.ToolName, "WebFetch", "Read", "Grep", "Glob"}

// deadBuiltinSearch is Claude Code's built-in WebSearch: executed server-side by
// Anthropic's API, so against llama-server it returns 0 results with no error.
// winc denies it (so the model never picks it) once the local tool is registered.
const deadBuiltinSearch = "WebSearch"

// EnsureClaudeLocal creates the isolated Claude Code config dir for the local instance,
// so it never touches the user's logged-in cloud Claude Code, and ensures the pre-approved
// tools are allowed in its settings.json. With searchOn the local search tool is allowed
// and the dead built-in WebSearch is moved from allow to deny; with it off the
// permissions are left exactly as they are (no local tool to point at). Returns the
// directory path. Idempotent.
func EnsureClaudeLocal(searchOn bool) (string, error) {
	dir := paths.ClaudeLocalDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	ensureToolPermissions(filepath.Join(dir, "settings.json"), searchOn)
	return dir, nil
}

// WriteMCPConfig (re)writes .claude-local/mcp.json registering THIS winc binary
// as the stdio MCP server "winc" (serving web_search via `winc mcp-search`).
// Regenerated every launch, like the agent notes, so the file never carries a
// stale path after the folder moves. Returns the file's path for --mcp-config.
func WriteMCPConfig(wincExe string) (string, error) {
	dir := paths.ClaudeLocalDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	p := filepath.Join(dir, "mcp.json")
	doc := map[string]any{
		"mcpServers": map[string]any{
			"winc": map[string]any{
				"type":    "stdio",
				"command": wincExe,
				"args":    []string{"mcp-search"},
			},
		},
	}
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", err
	}
	out = append(out, '\n')
	if cur, rerr := os.ReadFile(p); rerr == nil && string(cur) == string(out) {
		return p, nil // unchanged: don't touch the mtime
	}
	return p, os.WriteFile(p, out, 0o644)
}

// wincMarker is the first line of every winc-generated CLAUDE.md. The file is
// rewritten each launch ONLY while this marker leads it -- a user who edits the
// file owns it from then on and winc never touches it again.
const wincMarker = "<!-- generated by winc -->"

// WriteAgentNotes writes .claude-local/CLAUDE.md -- the sandboxed session's
// user-memory file, loaded into every conversation -- with the launch's
// MEASURED reality. The agent cannot learn any of this from its UI: Claude
// Code refuses window values under 100k tokens and displays a default instead
// (observed live: an agent that believed "26% of 100k" while its real 32k slot
// was full, truncating every file write silently). window is the server's
// loaded context; perSlot is what one request actually gets (halved under
// team escalation's --parallel 2); speeds may be 0 (unmeasured) and are then
// omitted.
// searchTool, when non-empty, is the local web search tool the model should
// use (the built-in WebSearch is dead on a local model).
func WriteAgentNotes(window, perSlot int, decodeTPS, promptTPS float64, searchTool string) error {
	dir := paths.ClaudeLocalDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	p := filepath.Join(dir, "CLAUDE.md")
	if data, err := os.ReadFile(p); err == nil {
		if !strings.HasPrefix(strings.TrimSpace(string(data)), wincMarker) {
			return nil // user-owned content -- never clobber
		}
	}
	var b strings.Builder
	b.WriteString(wincMarker + "\n# Local serving notes (winc)\n\n")
	if perSlot > 0 && perSlot < window {
		fmt.Fprintf(&b, "- Your REAL context window is %d tokens (a %d-token server window shared across slots).", perSlot, window)
	} else {
		fmt.Fprintf(&b, "- Your REAL context window is %d tokens.", window)
	}
	b.WriteString(" The context UI may claim a larger window (it cannot represent local windows below 100k) -- budget against the REAL number; overruns truncate output silently.\n")
	if decodeTPS > 0 {
		fmt.Fprintf(&b, "- Measured this launch: decode ~%.0f tok/s", decodeTPS)
		if promptTPS > 0 {
			fmt.Fprintf(&b, ", prompt processing ~%.0f tok/s", promptTPS)
		}
		b.WriteString(". Generation is slow: prefer several focused files/edits over one huge write; keep tool output small.\n")
	}
	if searchTool != "" {
		fmt.Fprintf(&b, "- Web search: use the %s tool (served locally by winc). The built-in WebSearch tool is UNAVAILABLE on a local model (it runs on Anthropic's servers and returns nothing here); it is denied in this sandbox.\n", searchTool)
	}
	b.WriteString(`- Small-window practices:
  - Persist working state EARLY: keep a NOTES.md with the goal, decisions, and next steps as you work. Re-read it after any compaction.
  - Prefer Grep and targeted reads over re-reading whole files.
  - Conversation that compaction dropped is archived in trimmed-context.md next to this file -- grep it to recover lost context.
  - After a compaction or restart: check the task list (TaskList) and your notes BEFORE asking the user what to do.
`)
	return os.WriteFile(p, []byte(b.String()), 0o644)
}

// ensureToolPermissions merges preApprovedTools into settings.json's permissions.allow,
// preserving any existing content, and -- when the local search tool is on -- moves the
// dead built-in WebSearch out of allow and into deny so existing sandboxes (which
// pre-1.43 winc had pre-approved it in) stop offering a tool that returns nothing.
// Idempotent; the user's other allow/deny rules are kept verbatim. Best-effort (a
// broken/missing file is replaced).
func ensureToolPermissions(path string, searchOn bool) {
	root := map[string]any{}
	if data, err := os.ReadFile(path); err == nil {
		_ = json.Unmarshal(data, &root) // tolerate empty/invalid -> start fresh
	}
	perms, _ := root["permissions"].(map[string]any)
	if perms == nil {
		perms = map[string]any{}
	}
	allow, _ := perms["allow"].([]any)
	have := map[string]bool{}
	for _, v := range allow {
		if s, ok := v.(string); ok {
			have[s] = true
		}
	}
	want := preApprovedTools
	if !searchOn {
		want = want[1:] // no local tool to point at: leave the search rules as they are
	}
	for _, t := range want {
		if !have[t] {
			allow = append(allow, t)
			have[t] = true
		}
	}
	if searchOn {
		kept := make([]any, 0, len(allow))
		for _, v := range allow {
			if s, ok := v.(string); ok && s == deadBuiltinSearch {
				continue
			}
			kept = append(kept, v)
		}
		allow = kept
		deny, _ := perms["deny"].([]any)
		denied := false
		for _, v := range deny {
			if s, ok := v.(string); ok && s == deadBuiltinSearch {
				denied = true
			}
		}
		if !denied {
			deny = append(deny, deadBuiltinSearch)
		}
		perms["deny"] = deny
	}
	perms["allow"] = allow
	root["permissions"] = perms
	if out, err := json.MarshalIndent(root, "", "  "); err == nil {
		_ = os.WriteFile(path, append(out, '\n'), 0o644)
	}
}

// WriteOpenCodeConfig (re)writes <install>/.opencode-local/opencode.json: the
// extra config OpenCode merges in through OPENCODE_CONFIG (between its global
// and project files, so the user's own OpenCode config is untouched). It
// registers THIS winc binary as the local MCP server "winc" (tools surface as
// winc_web_search) and points OpenCode's anthropic provider at winc's endpoint,
// which the env-only launch never did for OpenCode. Regenerated every launch.
func WriteOpenCodeConfig(wincExe, baseURL string) (string, error) {
	dir := filepath.Join(paths.InstallDir(), ".opencode-local")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	p := filepath.Join(dir, "opencode.json")
	doc := map[string]any{
		"$schema": "https://opencode.ai/config.json",
		"mcp": map[string]any{
			"winc": map[string]any{
				"type":    "local",
				"command": []string{wincExe, "mcp-search"},
				"enabled": true,
			},
		},
	}
	if baseURL != "" {
		doc["provider"] = map[string]any{
			"anthropic": map[string]any{
				"options": map[string]any{"baseURL": baseURL, "apiKey": "winc-local"},
			},
		}
	}
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", err
	}
	out = append(out, '\n')
	if cur, rerr := os.ReadFile(p); rerr == nil && string(cur) == string(out) {
		return p, nil
	}
	return p, os.WriteFile(p, out, 0o644)
}
