package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"winc/internal/paths"
)

// preApprovedTools are pre-allowed in the sandbox settings.json so the local agent (and
// every subagent it spawns, including Workflow fan-out) never prompts to use them each
// launch -- web search/fetch plus read-only inspection. Write/Edit/Bash stay prompt-on-use;
// the user's own deny rules still take precedence over these allows.
var preApprovedTools = []string{"WebSearch", "WebFetch", "Read", "Grep", "Glob"}

// EnsureClaudeLocal creates the isolated Claude Code config dir for the local instance,
// so it never touches the user's logged-in cloud Claude Code, and ensures the pre-approved
// tools are allowed in its settings.json. Returns the directory path. Idempotent.
func EnsureClaudeLocal() (string, error) {
	dir := paths.ClaudeLocalDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	ensureToolPermissions(filepath.Join(dir, "settings.json"))
	return dir, nil
}

// wincMarker is the first line of every winc-generated CLAUDE.md. The file is
// rewritten each launch ONLY while this marker leads it -- a user who edits the
// file owns it from then on and winc never touches it again.
const wincMarker = "<!-- generated by winc -->"

// WriteAgentNotes writes .claude-local/CLAUDE.md -- the sandboxed session's
// user-memory file, loaded into every conversation -- with the launch's
// MEASURED reality. The agent cannot learn any of this from its UI: Claude
// Code refuses window values under 100k tokens and displays a default instead
// (observed live: an agent that believed "26% of 100k" while its real 32k slot
// was full, truncating every file write silently). window is the server's
// loaded context; perSlot is what one request actually gets (halved under
// team escalation's --parallel 2); speeds may be 0 (unmeasured) and are then
// omitted.
func WriteAgentNotes(window, perSlot int, decodeTPS, promptTPS float64) error {
	dir := paths.ClaudeLocalDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	p := filepath.Join(dir, "CLAUDE.md")
	if data, err := os.ReadFile(p); err == nil {
		if !strings.HasPrefix(strings.TrimSpace(string(data)), wincMarker) {
			return nil // user-owned content -- never clobber
		}
	}
	var b strings.Builder
	b.WriteString(wincMarker + "\n# Local serving notes (winc)\n\n")
	if perSlot > 0 && perSlot < window {
		fmt.Fprintf(&b, "- Your REAL context window is %d tokens (a %d-token server window shared across slots).", perSlot, window)
	} else {
		fmt.Fprintf(&b, "- Your REAL context window is %d tokens.", window)
	}
	b.WriteString(" The context UI may claim a larger window (it cannot represent local windows below 100k) -- budget against the REAL number; overruns truncate output silently.\n")
	if decodeTPS > 0 {
		fmt.Fprintf(&b, "- Measured this launch: decode ~%.0f tok/s", decodeTPS)
		if promptTPS > 0 {
			fmt.Fprintf(&b, ", prompt processing ~%.0f tok/s", promptTPS)
		}
		b.WriteString(". Generation is slow: prefer several focused files/edits over one huge write; keep tool output small.\n")
	}
	b.WriteString(`- Small-window practices:
  - Persist working state EARLY: keep a NOTES.md with the goal, decisions, and next steps as you work. Re-read it after any compaction.
  - Prefer Grep and targeted reads over re-reading whole files.
  - Conversation that compaction dropped is archived in trimmed-context.md next to this file -- grep it to recover lost context.
  - After a compaction or restart: check the task list (TaskList) and your notes BEFORE asking the user what to do.
`)
	return os.WriteFile(p, []byte(b.String()), 0o644)
}

// ensureToolPermissions merges preApprovedTools into settings.json's permissions.allow,
// preserving any existing content. Best-effort (a broken/missing file is replaced).
func ensureToolPermissions(path string) {
	root := map[string]any{}
	if data, err := os.ReadFile(path); err == nil {
		_ = json.Unmarshal(data, &root) // tolerate empty/invalid -> start fresh
	}
	perms, _ := root["permissions"].(map[string]any)
	if perms == nil {
		perms = map[string]any{}
	}
	allow, _ := perms["allow"].([]any)
	have := map[string]bool{}
	for _, v := range allow {
		if s, ok := v.(string); ok {
			have[s] = true
		}
	}
	for _, t := range preApprovedTools {
		if !have[t] {
			allow = append(allow, t)
			have[t] = true
		}
	}
	perms["allow"] = allow
	root["permissions"] = perms
	if out, err := json.MarshalIndent(root, "", "  "); err == nil {
		_ = os.WriteFile(path, append(out, '\n'), 0o644)
	}
}
